apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: k8s4arch-hotels-diary-report
  namespace: unit4
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: k8s4arch-hotels-diary-report
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: ghcr.io/go-elevate/k8s4arch-hotels-backend:slim
            name: k8s4arch-hotels-diary-report
            command: ["python", "report.py"]
            resources: {}
          restartPolicy: OnFailure
  schedule: 0 2 * * *
status: {}
