apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8s4arch-hotels
  name: k8s4arch-hotels
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s4arch-hotels
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s4arch-hotels
        type: monolith
        version: v2
    spec:
      containers:
      - image: ghcr.io/go-elevate/k8s4arch-hotels:monolith-v2
        name: k8s4arch-hotels
        resources: {}
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
status: {}
